# Exercício- Household Electric Power Consumption


Medições do consumo de energia elétrica em uma residência com uma taxa de amostragem de um minuto, durante um período de quase 4 anos.  

* **Item 1)** Faça a análise exploratoria dos dados,preencha os valores faltantes com o valor da média da respectiva  feature.
* **Item 2)** Construa uma rede neural LSTM, com multiplas entradas, a saber:
  * **Atributos previsores:** 'Global_active_power', 'Global_reactive_power',   'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',      'Sub_metering_3.
  * **Atributos alvo:** 'Global_active_power', 'Global_reactive_power.
* **Item 3)** Avalie o desempenho do método.

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
energy_df = pd.read_csv('/content/drive/MyDrive/Redes_neurais_artificiais/Aula2_Redes_neurais_artificiais/Aula2.3 _Redes_neurais_recorrentes_lstm/energy_df.csv')

In [4]:
energy_df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [ ]:
energy_df.columns

In [5]:
# Atenção o data set contem valores faltantes
energy_df.isnull().sum()

Date                         0
Time                         0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64