# **Exercício LSTM - Daily Climate Time Series Data**


O "Daily Climate Time Series Data" é um conjunto de dados de séries temporais que contém registros climáticos diários da cidade de Delhi, Índia, no período de 1° de janeiro de 2013 a 31 de dezembro de 2017.



## **Características principais**
* Período: 2013–2017 (5 anos completos).

* Frequência: Diária.

* Localização: Delhi, Índia.

* Número de registros: 1.461 entradas (5 anos × 365 dias + 1 dia bissexto em 2016

## **Padrões e Sazonalidades Esperados**

* Temperatura (meantemp): Sazonalidade anual:
  * verões quentes (abril–junho: 30–40°C)
  * invernos frios (dezembro–fevereiro: 5–15°C).

* Tendência diária: variação entre dia e noite.

* Umidade (humidity):
  * Maior durante a monção (julho–setembro).
  * Menor no verão e inverno.

* Velocidade do Vento (wind_speed): Pode aumentar durante monções e tempestades.

* Pressão (meanpressure):
  * Varia com condições climáticas (ex.: baixa pressão indica possibilidade de chuva)

## **Atividade**


Item A) Construa uma rede neural LSTM  univarida, com adequada janela temporal a fim de prever  **meantemp**

item B) Construa uma rede neural LSTM  multivariada, com adequada janela temporal a fim de prever  **meantemp**, a partir das entradas  **meantemp**, 	**humidity**	**wind_speed**, 	**meanpressur**

item C) Construa uma rede neural LSTM  multivariada, com adequada janela temporal a fim de prever   **wind_speed**, 	**meanpressur**  partir das entradas  **meantemp**, 	**humidity**

## **Importação local do dataset**

In [10]:
import pandas as pd

In [11]:
base_treinamento =pd.read_csv('DailyDelhiClimateTest.csv')

In [12]:
base_teste =pd.read_csv('DailyDelhiClimateTrain.csv')

In [13]:
base_treinamento.head()

         date   meantemp   humidity  wind_speed  meanpressure
0  2017-01-01  15.913043  85.869565    2.743478     59.000000
1  2017-01-02  18.500000  77.222222    2.894444   1018.277778
2  2017-01-03  17.111111  81.888889    4.016667   1018.333333
3  2017-01-04  18.700000  70.050000    4.545000   1015.700000
4  2017-01-05  18.388889  74.944444    3.300000   1014.333333

In [14]:
base_teste.head()

         date   meantemp   humidity  wind_speed  meanpressure
0  2013-01-01  10.000000  84.500000    0.000000   1015.666667
1  2013-01-02   7.400000  92.000000    2.980000   1017.800000
2  2013-01-03   7.166667  87.000000    4.633333   1018.666667
3  2013-01-04   8.666667  71.333333    1.233333   1017.166667
4  2013-01-05   6.000000  86.833333    3.700000   1016.500000